"""Actual vs Budget variance (Epic 03 + Epic 04, master prompt SS8).

Reads the BUDGET version from data/budget.json (generated by
data/generate_budget.py) and compares it to ACTUAL from the ERP Adapter.
"""
from __future__ import annotations

import _adapter_path  # noqa: F401
import json
from dataclasses import dataclass
from datetime import date, timedelta
from pathlib import Path

from adapter import OdooERPAdapter
from pnl import compute_monthly_by_family

TODAY = date(2026, 8, 9)
FY_START = TODAY - timedelta(days=365)
_BUDGET_PATH = Path(__file__).resolve().parent / "data" / "budget.json"


@dataclass
class FamilyVariance:
    family: str
    actual_revenue: float
    budget_revenue: float
    revenue_variance: float
    revenue_variance_pct: float
    actual_cost: float
    budget_cost: float
    cost_variance: float
    cost_variance_pct: float


def load_budget() -> list[dict]:
    return json.loads(_BUDGET_PATH.read_text())


def actual_vs_budget(adapter: OdooERPAdapter) -> list[FamilyVariance]:
    budget_rows = load_budget()
    budget_by_family: dict[str, dict[str, float]] = {}
    for row in budget_rows:
        b = budget_by_family.setdefault(row["family"], {"revenue": 0.0, "cost": 0.0})
        b["revenue"] += row["revenue_budget"]
        b["cost"] += row["cost_budget"]

    actual_monthly = compute_monthly_by_family(adapter, date_from=FY_START, date_to=TODAY)
    actual_by_family: dict[str, dict[str, float]] = {}
    for (month, family), vals in actual_monthly.items():
        a = actual_by_family.setdefault(family, {"revenue": 0.0, "cogs": 0.0})
        a["revenue"] += vals["revenue"]
        a["cogs"] += vals["cogs"]

    results = []
    families = set(budget_by_family) | set(actual_by_family)
    for family in sorted(families):
        b = budget_by_family.get(family, {"revenue": 0.0, "cost": 0.0})
        a = actual_by_family.get(family, {"revenue": 0.0, "cogs": 0.0})
        rev_var = a["revenue"] - b["revenue"]
        cost_var = a["cogs"] - b["cost"]
        results.append(
            FamilyVariance(
                family=family,
                actual_revenue=round(a["revenue"], 2),
                budget_revenue=round(b["revenue"], 2),
                revenue_variance=round(rev_var, 2),
                revenue_variance_pct=round(rev_var / b["revenue"], 4) if b["revenue"] else 0.0,
                actual_cost=round(a["cogs"], 2),
                budget_cost=round(b["cost"], 2),
                cost_variance=round(cost_var, 2),
                cost_variance_pct=round(cost_var / b["cost"], 4) if b["cost"] else 0.0,
            )
        )
    return results


if __name__ == "__main__":
    rows = actual_vs_budget(OdooERPAdapter())
    print(f"{'Family':<32} {'Rev Var':>14} {'Rev Var%':>9}   {'Cost Var':>14} {'Cost Var%':>10}")
    for r in rows:
        print(
            f"{r.family:<32} {r.revenue_variance:>14,.0f} {r.revenue_variance_pct:>8.1%}   "
            f"{r.cost_variance:>14,.0f} {r.cost_variance_pct:>9.1%}"
        )
